# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='sc2creativity',
    version='0.1.0',
    python_requires='==3.*,>=3.8.0',
    author='Mike Axiak',
    author_email='mike@axiak.net',
    entry_points={
        "console_scripts": [
            "build_summaries = sc2creativity.features.summaries:build_summaries",
            "build_dataframes = sc2creativity.features.replay_dataframes:build_dataframes",
            "find_replay = sc2creativity.models.find_replay:find_replay"
        ]
    },
    packages=[
        'sc2creativity', 'sc2creativity.data', 'sc2creativity.features',
        'sc2creativity.models', 'sc2creativity.visualization'
    ],
    package_dir={"": "."},
    package_data={"sc2creativity": ["*.py~"]},
    install_requires=[
        'awscli==1.*,>=1.18.46', 'click==7.*,>=7.1.1', 'flake8==3.*,>=3.7.9',
        'jupyter==1.*,>=1.0.0', 'keras==2.*,>=2.3.1', 'matplotlib==3.*,>=3.2.1',
        'pandas==1.*,>=1.0.3', 'python-dotenv==0.*,>=0.13.0',
        'sc2reader==1.*,>=1.5.0', 'sphinx==3.*,>=3.0.2', 'tables==3.*,>=3.6.1',
        'tensorflow-gpu==2.2.0rc3', 'umap-learn[plot]==0.*,>=0.4.1'
    ],
    extras_require={"dev": ["pytest==5.*,>=5.2.0"]},
)
